import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LMS",
  description: "Generated by LMS",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
    const cookieHandler = await cookies()
    const userCookie = cookieHandler.get("user")

    const user = JSON.parse(userCookie?.value ?? "{}")
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full px-5 py-1 shadow-lg text-sky-900">
            <div className="w-full max-w-6xl mx-auto flex justify-between gap-5">
                <Link href="/"><h1 className="text-xl font-bold">Martian E-learning Management System</h1></Link>
                <h1 className="sm:text-xl sm:font-bold">{user.username}</h1>
            </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
